### ISSUE TITLE
Documentation is missing instructions on using S3 as provisioning interface.

### ISSUE THREAD

**Issue by evannadeau** [aws-samples/aws-sso-extensions-for-enterprise#33] opened 2022-01-19 16:47 UTC
Per the title, there is no information on how to use files into the S3 bucket as the provisioning interface.  I've been trying to work with the files provided, as well as what is already in the bucket from the SSO current state import, but it is not working out for me.  Using one of the files from **permissions_sets** folder, I get errors, and guessing at a proper format is not getting me any closer to deployment.

`{"Subject":"Error Processing Permission Set create/update via S3 Interface","eventDetail":{"eventVersion":"2.1","eventSource":"aws:s3","awsRegion":"us-west-2","eventTime":"2022-01-19T16:37:13.277Z","eventName":"ObjectCreated:Put","userIdentity":{"principalId":"_REDACTED_"},"requestParameters":{"sourceIPAddress":"_REDACTED_"},"responseElements":{_REDACTED_},"s3":{"s3SchemaVersion":"1.0","configurationId":"MjM2YmU4OWQtZDBlMC00NDI4LTgzZjEtYTFiM2QwNmU4M2Jk","bucket":{"name":"_REDACTED_","ownerIdentity":{"principalId":"_REDACTED_"},"arn":"_REDACTED_"},"object":{"key":"permission_sets/CloudOperators-ps-s3.json","size":1631,"eTag":"9826505bb7f8b0c45cc73d02d500e7c6","sequencer":"0061E83E3932B78E92"}}},"errorDetails":{"errors":[{"errorCode":"additionalProperties","message":"must NOT have additional properties"},{"errorCode":"required","message":"must have required property 'permissionSetName'"}]}}`

**Comment by evannadeau** [comment] 2022-01-19 17:02
I had a thought, that it was a whitespace issue, as the SSO current state import files are all single line, no whitespace.

I reformatted one of the example files to have no whitespace in the JSON file, but still the same error.

**Comment by leelalagudu** [comment] 2022-01-19 18:48
Hi @evannadeau , 

Thank you for raising this issue. 

I identified the root cause of the issue you are seeing and working on a fix which will be merged soon. For your reference, the handler that deals with S3 object actions for permission sets is using the API interface schema (which is incorrect) and causing the issue you're seeing. I am changing this to use the S3 interface schema as part of the PR.

With regards to the lack of documentation, I do agree that both our workshop and github repo are solely focussed on API interface only. As part of this PR, we will also add some documentation to guide through the usage of S3 interface for your use case flows.

Thank you,
Leela

**Closed** 2022-01-20 09:41 UTC
Labels: bug

**Comment by leelalagudu** [comment] 2022-01-20 09:46
Hi @evannadeau , [v3.0.1](https://github.com/aws-samples/aws-sso-extensions-for-enterprise/releases/tag/v3.0.1) should both fix the bug you're seeing as well as have more documentation around how to use S3 interface. 

Could you please take a look and let us know what you think?
